spring:
  application:
    name: leave_ms_bn
  datasource:
    url: jdbc:mysql://localhost:3306/leave_db?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!
  jpa:
    show-sql: true
  jwt:
    secret:  ${JWT_SECRET:W+ptkkoSFguUac5JraK5tBOXy0s3J9ktfiLMQj59fdM=}
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 2fefff72-473b-4a7d-ab17-b1066491eeed
            client-secret: L3i8Q~4xfLNKORisfte2SYsnpgeEmPq2lYPHudoC
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/azure"
            client-name: Microsoft
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me