spring:
  application:
    name: leave_ms_bn
  datasource:
    url: jdbc:mysql://localhost:3306/leave_db?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!
  jpa:
    show-sql: true
  jwt:
    secret:  ${JWT_SECRET}
